import { Product, Category } from '@/lib/types';

// Demo Categories
export const demoCategories: Category[] = [
  { id: '1', name: 'กาแฟร้อน', sort_order: 1, created_at: new Date().toISOString() },
  { id: '2', name: 'กาแฟเย็น', sort_order: 2, created_at: new Date().toISOString() },
  { id: '3', name: 'ชา', sort_order: 3, created_at: new Date().toISOString() },
  { id: '4', name: 'นม/โกโก้', sort_order: 4, created_at: new Date().toISOString() },
  { id: '5', name: 'ปั่น', sort_order: 5, created_at: new Date().toISOString() },
  { id: '6', name: 'ขนม', sort_order: 6, created_at: new Date().toISOString() },
];

// Demo Products
export const demoProducts: Product[] = [
  // กาแฟร้อน
  {
    id: '1',
    name: 'เอสเพรสโซ่',
    price: 40,
    category_id: '1',
    is_available: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '2',
    name: 'อเมริกาโน่ร้อน',
    price: 45,
    category_id: '1',
    is_available: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '3',
    name: 'ลาเต้ร้อน',
    price: 50,
    category_id: '1',
    is_available: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '4',
    name: 'คาปูชิโน่',
    price: 50,
    category_id: '1',
    is_available: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '5',
    name: 'มอคค่าร้อน',
    price: 55,
    category_id: '1',
    is_available: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },

  // กาแฟเย็น
  {
    id: '6',
    name: 'อเมริกาโน่เย็น',
    price: 50,
    category_id: '2',
    is_available: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '7',
    name: 'ลาเต้เย็น',
    price: 55,
    category_id: '2',
    is_available: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '8',
    name: 'มอคค่าเย็น',
    price: 60,
    category_id: '2',
    is_available: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '9',
    name: 'คาราเมลมัคคิอาโต้',
    price: 65,
    category_id: '2',
    is_available: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },

  // ชา
  {
    id: '10',
    name: 'ชาเขียวร้อน',
    price: 40,
    category_id: '3',
    is_available: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '11',
    name: 'ชาเขียวเย็น',
    price: 45,
    category_id: '3',
    is_available: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '12',
    name: 'ชาไทยร้อน',
    price: 40,
    category_id: '3',
    is_available: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '13',
    name: 'ชาไทยเย็น',
    price: 45,
    category_id: '3',
    is_available: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },

  // นม/โกโก้
  {
    id: '14',
    name: 'นมสดร้อน',
    price: 35,
    category_id: '4',
    is_available: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '15',
    name: 'นมสดเย็น',
    price: 40,
    category_id: '4',
    is_available: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '16',
    name: 'โกโก้ร้อน',
    price: 45,
    category_id: '4',
    is_available: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '17',
    name: 'โกโก้เย็น',
    price: 50,
    category_id: '4',
    is_available: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },

  // ปั่น
  {
    id: '18',
    name: 'กาแฟปั่น',
    price: 65,
    category_id: '5',
    is_available: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '19',
    name: 'ชาเขียวปั่น',
    price: 60,
    category_id: '5',
    is_available: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '20',
    name: 'โกโก้ปั่น',
    price: 60,
    category_id: '5',
    is_available: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '21',
    name: 'โอรีโอ้ปั่น',
    price: 65,
    category_id: '5',
    is_available: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },

  // ขนม
  {
    id: '22',
    name: 'ครัวซองค์',
    price: 45,
    category_id: '6',
    is_available: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '23',
    name: 'บราวนี่',
    price: 40,
    category_id: '6',
    is_available: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '24',
    name: 'คุกกี้',
    price: 25,
    category_id: '6',
    is_available: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];
